### ISSUE TITLE
improvement: amqp_serde design and APIs

### ISSUE THREAD

**Issue by gftea** [gftea/amqprs#70]
tracking remainig work of #64 

- [x] for MapSerializer, add test for !self.is_len_known #71 
- [x] for the types.rs, add tests for len of FieldValue variants A F x - #76 

- [x] improvements: - #77  merged into branch `release_v2` 
   - Create a new PR to: 
       1. Remove insert/remove functions.
       2. Make impl TryFrom.
       3. Remove length attribute from ByteArray and FieldArray, FieldTable and impl len function instead.
       4. Modify/Add tests.
